package com.judahben149.fourthwall.utils

import android.content.Context
import com.judahben149.fourthwall.R
import com.judahben149.fourthwall.domain.models.CurrencyPair
import com.murgupluoglu.flagkit.FlagKit
import java.text.NumberFormat
import java.util.Currency
import java.util.Locale

object CurrencyUtils {

    private val supportedCurrencyPairs = listOf(
        CurrencyPair("GHS", "USDC"),
        CurrencyPair("NGN", "KES"),
        CurrencyPair("KES", "USD"),
        CurrencyPair("USD", "KES"),
        CurrencyPair("USD", "EUR"),
        CurrencyPair("EUR", "USD"),
        CurrencyPair("USD", "GBP"),
        CurrencyPair("USD", "BTC"),
        CurrencyPair("EUR", "USDC"),
        CurrencyPair("EUR", "GBP"),
        CurrencyPair("USD", "AUD"),
        CurrencyPair("USD", "MXN")
    )

    fun getCurrencyName(currencyCode: String, locale: Locale = Locale.getDefault()): String? {
        return try {
            when(currencyCode) {
                "USDC" -> "USD Coin"
                "BTC" -> "Bitcoin"

                else -> {
                    val currency = Currency.getInstance(currencyCode)
                    currency.getDisplayName(locale)
                }
            }
        } catch (ex: Exception) {
            null
        }
    }

    private fun getCountryCode(currencyCode: String): String? {
        currencyToCountryMap[currencyCode]?.let { return it }

        return try {
            val currency = Currency.getInstance(currencyCode)
            val locale = Locale.getAvailableLocales().find {
                locale -> currency == Currency.getInstance(locale)
            }

            locale?.country
        } catch (e: IllegalArgumentException) {
            null
        }
    }

    fun getCountryFlag(context: Context, currencyCode: String): Int? {
        if (currencyCode == "BTC") return R.drawable.ic_btc
        if (currencyCode == "USDC") return R.drawable.ic_usdc_logo

        val countryCode = getCountryCode(currencyCode)
        return countryCode?.let { FlagKit.getResId(context, it) }
    }

    private val currencyToCountryMap: Map<String, String> = mapOf(
        "AED" to "AE",
        "AFN" to "AF",
        "ALL" to "AL",
        "AMD" to "AM",
        "ANG" to "CW",
        "AOA" to "AO",
        "ARS" to "AR",
        "AUD" to "AU",
        "AWG" to "AW",
        "AZN" to "AZ",
        "BAM" to "BA",
        "BBD" to "BB",
        "BDT" to "BD",
        "BGN" to "BG",
        "BHD" to "BH",
        "BIF" to "BI",
        "BMD" to "BM",
        "BND" to "BN",
        "BOB" to "BO",
        "BRL" to "BR",
        "BSD" to "BS",
        "BTN" to "BT",
        "BWP" to "BW",
        "BYN" to "BY",
        "BZD" to "BZ",
        "CAD" to "CA",
        "CDF" to "CD",
        "CHF" to "CH",
        "CLP" to "CL",
        "CNY" to "CN",
        "COP" to "CO",
        "CRC" to "CR",
        "CUP" to "CU",
        "CVE" to "CV",
        "CZK" to "CZ",
        "DJF" to "DJ",
        "DKK" to "DK",
        "DOP" to "DO",
        "DZD" to "DZ",
        "EGP" to "EG",
        "ERN" to "ER",
        "ETB" to "ET",
        "EUR" to "EU",
        "FJD" to "FJ",
        "FKP" to "FK",
        "GBP" to "GB",
        "GEL" to "GE",
        "GHS" to "GH",
        "GIP" to "GI",
        "GMD" to "GM",
        "GNF" to "GN",
        "GTQ" to "GT",
        "GYD" to "GY",
        "HKD" to "HK",
        "HNL" to "HN",
        "HRK" to "HR",
        "HTG" to "HT",
        "HUF" to "HU",
        "IDR" to "ID",
        "ILS" to "IL",
        "INR" to "IN",
        "IQD" to "IQ",
        "IRR" to "IR",
        "ISK" to "IS",
        "JMD" to "JM",
        "JOD" to "JO",
        "JPY" to "JP",
        "KES" to "KE",
        "KGS" to "KG",
        "KHR" to "KH",
        "KMF" to "KM",
        "KPW" to "KP",
        "KRW" to "KR",
        "KWD" to "KW",
        "KYD" to "KY",
        "KZT" to "KZ",
        "LAK" to "LA",
        "LBP" to "LB",
        "LKR" to "LK",
        "LRD" to "LR",
        "LSL" to "LS",
        "LYD" to "LY",
        "MAD" to "MA",
        "MDL" to "MD",
        "MGA" to "MG",
        "MKD" to "MK",
        "MMK" to "MM",
        "MNT" to "MN",
        "MOP" to "MO",
        "MRU" to "MR",
        "MUR" to "MU",
        "MVR" to "MV",
        "MWK" to "MW",
        "MXN" to "MX",
        "MYR" to "MY",
        "MZN" to "MZ",
        "NAD" to "NA",
        "NGN" to "NG",
        "NIO" to "NI",
        "NOK" to "NO",
        "NPR" to "NP",
        "NZD" to "NZ",
        "OMR" to "OM",
        "PAB" to "PA",
        "PEN" to "PE",
        "PGK" to "PG",
        "PHP" to "PH",
        "PKR" to "PK",
        "PLN" to "PL",
        "PYG" to "PY",
        "QAR" to "QA",
        "RON" to "RO",
        "RSD" to "RS",
        "RUB" to "RU",
        "RWF" to "RW",
        "SAR" to "SA",
        "SBD" to "SB",
        "SCR" to "SC",
        "SDG" to "SD",
        "SEK" to "SE",
        "SGD" to "SG",
        "SHP" to "SH",
        "SLL" to "SL",
        "SOS" to "SO",
        "SRD" to "SR",
        "SSP" to "SS",
        "STN" to "ST",
        "SVC" to "SV",
        "SYP" to "SY",
        "SZL" to "SZ",
        "THB" to "TH",
        "TJS" to "TJ",
        "TMT" to "TM",
        "TND" to "TN",
        "TOP" to "TO",
        "TRY" to "TR",
        "TTD" to "TT",
        "TWD" to "TW",
        "TZS" to "TZ",
        "UAH" to "UA",
        "UGX" to "UG",
        "USD" to "US",
        "UYU" to "UY",
        "UZS" to "UZ",
        "VES" to "VE",
        "VND" to "VN",
        "VUV" to "VU",
        "WST" to "WS",
        "XAF" to "CM",
        "XCD" to "AG",
        "XOF" to "BJ",
        "XPF" to "PF",
        "YER" to "YE",
        "ZAR" to "ZA",
        "ZMW" to "ZM",
        "ZWL" to "ZW"
    )

    val currencies = listOf(
        "AED" to "United Arab Emirates Dirham",
        "AFN" to "Afghan Afghani",
        "ALL" to "Albanian Lek",
        "AMD" to "Armenian Dram",
        "ANG" to "Netherlands Antillean Guilder",
        "AOA" to "Angolan Kwanza",
        "ARS" to "Argentine Peso",
        "AUD" to "Australian Dollar",
        "AWG" to "Aruban Florin",
        "AZN" to "Azerbaijani Manat",
        "BAM" to "Bosnia-Herzegovina Convertible Mark",
        "BBD" to "Barbadian Dollar",
        "BDT" to "Bangladeshi Taka",
        "BGN" to "Bulgarian Lev",
        "BHD" to "Bahraini Dinar",
        "BIF" to "Burundian Franc",
        "BMD" to "Bermudan Dollar",
        "BND" to "Brunei Dollar",
        "BOB" to "Bolivian Boliviano",
        "BRL" to "Brazilian Real",
        "BSD" to "Bahamian Dollar",
        "BTC" to "Bitcoin",
        "BTN" to "Bhutanese Ngultrum",
        "BWP" to "Botswanan Pula",
        "BYN" to "Belarusian Ruble",
        "BZD" to "Belize Dollar",
        "CAD" to "Canadian Dollar",
        "CDF" to "Congolese Franc",
        "CHF" to "Swiss Franc",
        "CLP" to "Chilean Peso",
        "CNY" to "Chinese Yuan",
        "COP" to "Colombian Peso",
        "CRC" to "Costa Rican Colón",
        "CUC" to "Cuban Convertible Peso",
        "CUP" to "Cuban Peso",
        "CVE" to "Cape Verdean Escudo",
        "CZK" to "Czech Republic Koruna",
        "DJF" to "Djiboutian Franc",
        "DKK" to "Danish Krone",
        "DOP" to "Dominican Peso",
        "DZD" to "Algerian Dinar",
        "EGP" to "Egyptian Pound",
        "ERN" to "Eritrean Nakfa",
        "ETB" to "Ethiopian Birr",
        "EUR" to "Euro",
        "FJD" to "Fijian Dollar",
        "FKP" to "Falkland Islands Pound",
        "GBP" to "British Pound Sterling",
        "GEL" to "Georgian Lari",
        "GGP" to "Guernsey Pound",
        "GHS" to "Ghanaian Cedi",
        "GIP" to "Gibraltar Pound",
        "GMD" to "Gambian Dalasi",
        "GNF" to "Guinean Franc",
        "GTQ" to "Guatemalan Quetzal",
        "GYD" to "Guyanaese Dollar",
        "HKD" to "Hong Kong Dollar",
        "HNL" to "Honduran Lempira",
        "HRK" to "Croatian Kuna",
        "HTG" to "Haitian Gourde",
        "HUF" to "Hungarian Forint",
        "IDR" to "Indonesian Rupiah",
        "ILS" to "Israeli New Sheqel",
        "IMP" to "Manx pound",
        "INR" to "Indian Rupee",
        "IQD" to "Iraqi Dinar",
        "IRR" to "Iranian Rial",
        "ISK" to "Icelandic Króna",
        "JEP" to "Jersey Pound",
        "JMD" to "Jamaican Dollar",
        "JOD" to "Jordanian Dinar",
        "JPY" to "Japanese Yen",
        "KES" to "Kenyan Shilling",
        "KGS" to "Kyrgystani Som",
        "KHR" to "Cambodian Riel",
        "KMF" to "Comorian Franc",
        "KPW" to "North Korean Won",
        "KRW" to "South Korean Won",
        "KWD" to "Kuwaiti Dinar",
        "KYD" to "Cayman Islands Dollar",
        "KZT" to "Kazakhstani Tenge",
        "LAK" to "Laotian Kip",
        "LBP" to "Lebanese Pound",
        "LKR" to "Sri Lankan Rupee",
        "LRD" to "Liberian Dollar",
        "LSL" to "Lesotho Loti",
        "LYD" to "Libyan Dinar",
        "MAD" to "Moroccan Dirham",
        "MDL" to "Moldovan Leu",
        "MGA" to "Malagasy Ariary",
        "MKD" to "Macedonian Denar",
        "MMK" to "Myanma Kyat",
        "MNT" to "Mongolian Tugrik",
        "MOP" to "Macanese Pataca",
        "MRO" to "Mauritanian Ouguiya",
        "MUR" to "Mauritian Rupee",
        "MVR" to "Maldivian Rufiyaa",
        "MWK" to "Malawian Kwacha",
        "MXN" to "Mexican Peso",
        "MYR" to "Malaysian Ringgit",
        "MZN" to "Mozambican Metical",
        "NAD" to "Namibian Dollar",
        "NGN" to "Nigerian Naira",
        "NIO" to "Nicaraguan Córdoba",
        "NOK" to "Norwegian Krone",
        "NPR" to "Nepalese Rupee",
        "NZD" to "New Zealand Dollar",
        "OMR" to "Omani Rial",
        "PAB" to "Panamanian Balboa",
        "PEN" to "Peruvian Nuevo Sol",
        "PGK" to "Papua New Guinean Kina",
        "PHP" to "Philippine Peso",
        "PKR" to "Pakistani Rupee",
        "PLN" to "Polish Zloty",
        "PYG" to "Paraguayan Guarani",
        "QAR" to "Qatari Rial",
        "RON" to "Romanian Leu",
        "RSD" to "Serbian Dinar",
        "RUB" to "Russian Ruble",
        "RWF" to "Rwandan Franc",
        "SAR" to "Saudi Riyal",
        "SBD" to "Solomon Islands Dollar",
        "SCR" to "Seychellois Rupee",
        "SDG" to "Sudanese Pound",
        "SEK" to "Swedish Krona",
        "SGD" to "Singapore Dollar",
        "SHP" to "Saint Helena Pound",
        "SLL" to "Sierra Leonean Leone",
        "SOS" to "Somali Shilling",
        "SRD" to "Surinamese Dollar",
        "STD" to "São Tomé and Príncipe Dobra",
        "SVC" to "Salvadoran Colón",
        "SYP" to "Syrian Pound",
        "SZL" to "Swazi Lilangeni",
        "THB" to "Thai Baht",
        "TJS" to "Tajikistani Somoni",
        "TMT" to "Turkmenistani Manat",
        "TND" to "Tunisian Dinar",
        "TOP" to "Tongan Pa'anga",
        "TRY" to "Turkish Lira",
        "TTD" to "Trinidad and Tobago Dollar",
        "TWD" to "New Taiwan Dollar",
        "TZS" to "Tanzanian Shilling",
        "UAH" to "Ukrainian Hryvnia",
        "UGX" to "Ugandan Shilling",
        "USD" to "United States Dollar",
        "USDC" to "USD Coin",
        "UYU" to "Uruguayan Peso",
        "UZS" to "Uzbekistan Som",
        "VEF" to "Venezuelan Bolívar Fuerte",
        "VND" to "Vietnamese Dong",
        "VUV" to "Vanuatu Vatu",
        "WST" to "Samoan Tala",
        "XAF" to "CFA Franc BEAC",
        "XAG" to "Silver (troy ounce)",
        "XAU" to "Gold (troy ounce)",
        "XCD" to "East Caribbean Dollar",
        "XDR" to "Special Drawing Rights",
        "XOF" to "CFA Franc BCEAO",
        "XPF" to "CFP Franc",
        "YER" to "Yemeni Rial",
        "ZAR" to "South African Rand",
        "ZMW" to "Zambian Kwacha",
        "ZWL" to "Zimbabwean Dollar"
    )

    fun Double.formatCurrency(currencyCode: String): String {
        return try {
            val format = NumberFormat.getCurrencyInstance(Locale.getDefault())
            val currency = Currency.getInstance(currencyCode)
            format.currency = currency
            format.maximumFractionDigits = currency.defaultFractionDigits
            format.format(this)
        } catch (ex: Exception) {
            this.toString()
        }
    }
}